version: "1.1:db"
services:
  postgres:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_DB: roomEase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Icaro06$
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
